CREATE TABLE conselhos_particulares (
                                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                        name VARCHAR(50) NOT NULL
);