CREATE TABLE conferencias (
                              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              nome VARCHAR(100) NOT NULL,
                              conselho_particular_id BIGINT NOT NULL,

                              CONSTRAINT fk_conferencia_conselho
                                  FOREIGN KEY (conselho_particular_id)
                                      REFERENCES conselhos_particulares(id)
);