CREATE TABLE assistidos (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            nome VARCHAR(100) NOT NULL,
                            cpf VARCHAR(15) NOT NULL UNIQUE,
                            pin VARCHAR(255) NOT NULL,
                            saldo DECIMAL(10,2) NOT NULL DEFAULT 0,
                            conferencia_id BIGINT NOT NULL,

                            CONSTRAINT fk_assistido_conferencia
                                FOREIGN KEY (conferencia_id)
                                    REFERENCES conferencias(id)
);