CREATE TABLE vicentinos (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            conselho_particular_id BIGINT NOT NULL UNIQUE,
                            senha VARCHAR(255) NOT NULL,

                            CONSTRAINT fk_vicentino_conselho
                                FOREIGN KEY (conselho_particular_id)
                                    REFERENCES conselhos_particulares(id)
);