CREATE TABLE produtos (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          nome VARCHAR(50) NOT NULL,
                          preco DECIMAL(10,2) NOT NULL
);