CREATE TABLE pedidos (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         assistido_id BIGINT NOT NULL,
                         status VARCHAR(50) NOT NULL,
                         mes_referencia INTEGER NOT NULL,
                         ano_referencia INTEGER NOT NULL,
                         data_criacao DATE NOT NULL,

                         CONSTRAINT fk_pedido_assistido
                             FOREIGN KEY (assistido_id)
                                 REFERENCES assistidos(id)
);