CREATE TABLE pedido_itens (
                              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              pedido_id BIGINT NOT NULL,
                              produto_id BIGINT NOT NULL,
                              quantidade INTEGER NOT NULL,
                              preco_unitario DECIMAL(10,2) NOT NULL,

                              CONSTRAINT fk_item_pedido
                                  FOREIGN KEY (pedido_id)
                                      REFERENCES pedidos(id),

                              CONSTRAINT fk_item_produto
                                  FOREIGN KEY (produto_id)
                                      REFERENCES produtos(id),

                              CONSTRAINT uk_item UNIQUE (pedido_id, produto_id)
);